[package]
name = "sergii_bondar_dummy_crate"
license = "MIT"
description = "Nothing special, just learning rust."
version = "0.1.0"
edition = "2024"

[dependencies]
trpl = "0.3.0"
futures = "0.3"
hello_macro = { path = "hello_macro" }
hello_macro_derive = { path = "hello_macro/hello_macro_derive" }


