[package]
name = "sergii_bondar_dummy_crate"
license = "MIT"
description = "Nothing special, just learning rust."
version = "0.1.0"
edition = "2024"

[dependencies]
trpl = "0.3.0"
futures = "0.3"
anyhow = "1.0.100"
lazy_static = "1.4"


